USE University_Student_Management_System;

INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_1', 'Electronics', '2007-03-24', 'Others');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_2', 'Computer Science', '2006-05-07', 'Others');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_3', 'Civil', '2003-06-14', 'Female');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_4', 'Mathematics', '2003-02-05', 'Male');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_5', 'Electronics', '2006-07-02', 'Male');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_6', 'Mathematics', '2005-08-07', 'Male');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_7', 'Electronics', '2004-12-19', 'Others');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_8', 'Mathematics', '2003-05-19', 'Male');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_9', 'Mechanical', '2004-04-23', 'Others');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_10', 'Mathematics', '2002-01-14', 'Female');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_11', 'Mechanical', '2007-05-18', 'Female');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_12', 'Electronics', '2007-01-07', 'Others');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_13', 'Electronics', '2002-09-06', 'Female');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_14', 'Civil', '2003-09-25', 'Male');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_15', 'Computer Science', '2007-06-17', 'Female');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_16', 'Mechanical', '2004-11-09', 'Male');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_17', 'Electronics', '2003-09-08', 'Male');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_18', 'Mechanical', '2005-11-01', 'Female');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_19', 'Civil', '2002-02-17', 'Male');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_20', 'Electronics', '2005-05-06', 'Female');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_21', 'Civil', '2002-03-05', 'Male');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_22', 'Mechanical', '2003-04-28', 'Female');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_23', 'Computer Science', '2004-05-31', 'Female');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_24', 'Computer Science', '2002-01-21', 'Male');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_25', 'Computer Science', '2003-02-12', 'Male');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_26', 'Computer Science', '2005-08-11', 'Others');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_27', 'Mathematics', '2003-01-10', 'Others');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_28', 'Electronics', '2006-05-31', 'Others');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_29', 'Civil', '2004-12-12', 'Female');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_30', 'Mathematics', '2002-07-28', 'Male');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_31', 'Civil', '2002-06-29', 'Others');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_32', 'Mathematics', '2007-05-15', 'Female');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_33', 'Electronics', '2006-01-05', 'Female');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_34', 'Mathematics', '2006-01-30', 'Male');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_35', 'Computer Science', '2003-07-30', 'Female');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_36', 'Mathematics', '2004-06-20', 'Male');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_37', 'Electronics', '2005-11-09', 'Others');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_38', 'Computer Science', '2006-08-13', 'Male');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_39', 'Computer Science', '2002-10-07', 'Male');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_40', 'Mechanical', '2004-11-16', 'Others');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_41', 'Computer Science', '2004-12-12', 'Male');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_42', 'Mathematics', '2004-04-05', 'Female');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_43', 'Mathematics', '2004-04-03', 'Male');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_44', 'Civil', '2004-08-22', 'Others');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_45', 'Computer Science', '2006-03-15', 'Female');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_46', 'Mathematics', '2004-12-01', 'Female');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_47', 'Civil', '2002-08-03', 'Female');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_48', 'Civil', '2002-08-10', 'Others');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_49', 'Civil', '2005-02-17', 'Male');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_50', 'Civil', '2005-01-06', 'Male');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_51', 'Mathematics', '2004-05-14', 'Male');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_52', 'Mathematics', '2003-10-24', 'Others');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_53', 'Civil', '2005-10-12', 'Others');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_54', 'Mathematics', '2005-08-31', 'Others');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_55', 'Mathematics', '2006-11-29', 'Others');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_56', 'Electronics', '2002-09-25', 'Male');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_57', 'Computer Science', '2005-06-15', 'Others');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_58', 'Mechanical', '2004-11-15', 'Male');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_59', 'Civil', '2005-10-28', 'Male');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_60', 'Mechanical', '2003-05-02', 'Female');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_61', 'Mechanical', '2002-02-13', 'Female');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_62', 'Civil', '2005-05-18', 'Male');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_63', 'Civil', '2003-08-12', 'Male');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_64', 'Computer Science', '2005-12-07', 'Female');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_65', 'Mathematics', '2005-06-03', 'Male');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_66', 'Mechanical', '2003-03-13', 'Male');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_67', 'Mechanical', '2004-05-27', 'Others');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_68', 'Mechanical', '2003-12-15', 'Female');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_69', 'Electronics', '2005-01-11', 'Others');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_70', 'Mathematics', '2002-03-28', 'Female');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_71', 'Civil', '2005-03-31', 'Male');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_72', 'Computer Science', '2007-03-24', 'Female');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_73', 'Mathematics', '2005-09-09', 'Others');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_74', 'Mathematics', '2004-05-05', 'Female');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_75', 'Mechanical', '2006-01-14', 'Others');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_76', 'Mathematics', '2002-01-01', 'Male');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_77', 'Civil', '2004-06-14', 'Others');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_78', 'Mechanical', '2004-04-27', 'Male');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_79', 'Civil', '2002-10-03', 'Female');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_80', 'Mathematics', '2004-04-20', 'Male');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_81', 'Electronics', '2006-05-04', 'Male');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_82', 'Mathematics', '2003-08-28', 'Others');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_83', 'Mathematics', '2003-05-24', 'Others');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_84', 'Civil', '2006-11-22', 'Male');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_85', 'Electronics', '2006-01-07', 'Male');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_86', 'Computer Science', '2004-08-14', 'Female');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_87', 'Mechanical', '2002-04-14', 'Female');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_88', 'Mechanical', '2007-02-04', 'Others');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_89', 'Mechanical', '2004-10-15', 'Others');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_90', 'Electronics', '2007-04-05', 'Others');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_91', 'Mechanical', '2002-12-26', 'Female');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_92', 'Mechanical', '2005-02-03', 'Male');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_93', 'Mathematics', '2002-03-21', 'Female');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_94', 'Mathematics', '2005-04-12', 'Male');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_95', 'Civil', '2005-03-30', 'Others');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_96', 'Computer Science', '2002-07-21', 'Female');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_97', 'Computer Science', '2004-09-15', 'Others');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_98', 'Computer Science', '2004-11-16', 'Others');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_99', 'Mechanical', '2007-03-17', 'Male');
INSERT INTO Students (Name, Department, DOB, Gender) VALUES ('Student_100', 'Mathematics', '2005-12-01', 'Male');